### PR TITLE
Add CI testing of unittests and linting

### LINKED ISSUE #1: Setup CI using Github Actions
There is a CI config using Travis-CI (`travis.yml`) in the repo, which comes from the upstream repo.

This should be ported to GitHub Actions.

### PR DESCRIPTION
**Pull request by andrewphilipsmith**
Initially, add whitespace and pretty-print formatters.

### CODE REVIEW

**Comment by andrewphilipsmith** [comment]
@crangelsmith - I think that this is now ready to merge.

This reproduces in GitHub Actions _some_ of the tests that are run in Travis-CI in `monitoring-ecosystem-resilience`.

* Only tests relevant to `pyveg` are reproduced. None of the tests relevant to `rveg` are run.
* Due to issue #19, one of the tests fails in CI (`pytest pyveg/tests/test_combiner_modules.py::test_combine`). In my opinion, this is due to a bug in the production code, not the CI or the tests. For now, the relevant test is skipped on CI but still runs locally.

Additionally, this PR adds linting rules via `pre-commit` (black, isort, autopep8, various whitespace formatters). These rules are repeated on the CI. As a result, this PR touches a lot of files - though most of these changes are minor. (With the benefit of hindsight I think that this should have been two separate PRs).

If/when merged, this PR would close #1.

**Review by crangelsmith — APPROVED** [review]
LGTM! 

I see the pre-commit hooks checks are failing after updating main with PR #14 , anything I should do on that front?

**Comment by andrewphilipsmith** [comment]
> I see the pre-commit hooks checks are failing after updating main with PR #14 , anything I should do on that front?

Not for now thanks - I'm working on this and will let you know if there is anything.

**Comment by andrewphilipsmith** [comment]
I have disabled a second test on CI, due to issue #20. In this case, I suspect (though haven't confirmed) that the problem is with the test code, not the CI or the production code.

In order to complete this PR, I've opted to disable the test on CI, rather than delay implementing the rest of the CI/liniting checks.

**Pull request merged**
